#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require_relative 'zigbee_types'

module ReportService
  class Client
    include ::Thrift::Client

    def sendReport(command)
      send_sendReport(command)
    end

    def send_sendReport(command)
      send_message('sendReport', SendReport_args, :command => command)
    end
  end

  class Processor
    include ::Thrift::Processor

    def process_sendReport(seqid, iprot, oprot)
      args = read_args(iprot, SendReport_args)
      @handler.sendReport(args.command)
      return
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class SendReport_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    COMMAND = 1

    FIELDS = {
      COMMAND => {:type => ::Thrift::Types::STRUCT, :name => 'command', :class => ::ReportCommandRequest}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class SendReport_result
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

